[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pre = "blogger"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "项目"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "探索"
  pageRef = "explore"
  weight = 40

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 50
