[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "專案"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "探索"
  pageRef = "explore"
  weight = 40

[[main]]
  name = "關於"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "網站紀錄"
  pageRef = "site-log"
  weight = 90
