[contentSecurityPolicy]
  script-src = [
    "'self'",
    "https://cusdis.com",
  ]
  frame-src = [
    "'self'",
    "https://cusdis.com",
  ]
  connect-src = [
    "'self'",
    "https://cusdis.com",
  ]
